# Site settings
title: Michael Stezycki
tagline: "Designer"
email: ahoy@stezycki.com
description: > # this means to ignore newlines until "baseurl:"
  Apps and websites from London based designer, @Mr_Stezz
keywords: "design, ux, ui, product, web, app, html, css, interaction, photography, london, uk"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stez.me" # the base hostname & protocol for your site
twitter_username: mr_stezz
github_username:  mr-stezz
repo: "https://github.com/mr-stezz/mr-stezz.github.io"

# Build settings
markdown: redcarpet
pygments: true
permalink: pretty
paginate: 1
