# Site settings
title: Michael Stezycki
tagline: "Designer"
email: ahoy@stezycki.com
description: Apps and websites from London based designer, @Mr_Stezz
keywords: "design, ux, ui, ix, product, business, strategy, web, app, html, css, interaction, photography, london, uk"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stez.me" # the base hostname & protocol for your site
github_username:  mr-stezz
repo: "https://github.com/mr-stezz/mr-stezz.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 0
